## 1.协方差矩阵
`cov = np.cov(X)` 的作用是**计算矩阵 X 的协方差矩阵**。

具体来说：

- `np.cov()` 是 NumPy 中计算协方差矩阵的函数。
- 输入 `X` 通常是一个数据矩阵，其中**每一行代表一个变量（特征），每一列代表一个观测样本**。
- 输出 `cov` 是一个方阵，其元素 `(i, j)` 表示第 `i` 个变量和第 `j` 个变量之间的协方差。对角线上的元素是各变量自身的方差。

**举个简单例子：**



In [1]:
import numpy as np
X = np.array([[1, 2, 3],
              [4, 5, 6]])  # 2个变量，3个样本

cov = np.cov(X)
print(cov)

[[1. 1.]
 [1. 1.]]




这里 `X` 有 2 行（2 个变量），3 列（3 个样本）。结果是一个 2x2 的协方差矩阵：
- 左上角和右下角：变量自身的方差
- 右上角和左下角：两个变量之间的协方差

**需要注意的一点：** `np.cov()` 默认使用 `bias=0`（即除以 `n-1`），计算的是**无偏估计**（样本协方差），而不是除以 `n` 的有偏版本。

## 2.协方差计算

你的代码：

```python
import numpy as np

X = np.array([
    [1, 2, 3],
    [4, 5, 6]
])  # 2个变量，3个样本

cov = np.cov(X)
print(cov)
```

输出是：

```python
[[1. 1.]
 [1. 1.]]
```

---

#### 2.1 X 的含义

矩阵：

$$
X=
\begin{bmatrix}
1 & 2 & 3 \\
4 & 5 & 6
\end{bmatrix}
$$

在 `np.cov(X)` 中，默认：

$$
\text{每一行表示一个变量}
$$

$$
\text{每一列表示一个样本}
$$

所以这里是：

$$
x_1 = [1,2,3]
$$

$$
x_2 = [4,5,6]
$$

也就是：

| 变量    | 样本 1 | 样本 2 | 样本 3 |
| ---: | ---: | ---: | ---: |
| $$x_1$$ |  1 |  2 |  3 |
| $$x_2$$ |  4 |  5 |  6 |

---

#### 2.2 先求每个变量的均值

第一个变量：

$$
\bar{x}_1 = \frac{1+2+3}{3}=2
$$

第二个变量：

$$
\bar{x}_2 = \frac{4+5+6}{3}=5
$$

---

#### 2.3 对每个变量去均值

第一个变量去均值：

$$
x_1 - \bar{x}_1 = [1-2,\ 2-2,\ 3-2]
= [-1,\ 0,\ 1]
$$

第二个变量去均值：

$$
x_2 - \bar{x}_2 = [4-5,\ 5-5,\ 6-5]
= [-1,\ 0,\ 1]
$$

所以中心化后的矩阵是：

$$
X_c=
\begin{bmatrix}
-1 & 0 & 1 \\
-1 & 0 & 1
\end{bmatrix}
$$

---

#### 2.4 协方差公式

两个变量 $$x$$ 和 $$y$$ 的样本协方差是：

$$
\operatorname{cov}(x,y)
=
\frac{1}{N-1}
\sum_{i=1}^{N}
(x_i-\bar{x})(y_i-\bar{y})
$$

这里：

$$
N=3
$$

所以分母是：

$$
N-1=2
$$

注意：`np.cov` 默认计算的是**样本协方差**，所以除以 $$N-1$$，不是除以 $$N$$。

---

#### 2.5 协方差矩阵长什么样

因为有两个变量：

$$
x_1
$$

和

$$
x_2
$$

所以协方差矩阵是一个 $$2 \times 2$$ 矩阵：

$$
C=
\begin{bmatrix}
\operatorname{cov}(x_1,x_1) & \operatorname{cov}(x_1,x_2) \
\operatorname{cov}(x_2,x_1) & \operatorname{cov}(x_2,x_2)
\end{bmatrix}
$$

---

#### 2.6 逐项计算

###### 2.6.1 左上角：$$\operatorname{cov}(x_1,x_1)$$

$$
\operatorname{cov}(x_1,x_1)
=
\frac{(-1)(-1)+0\cdot0+1\cdot1}{2}
$$

$$
\frac{1+0+1}{2}
=1
$$

这就是变量 $$x_1$$ 的样本方差。

---

##### 2.6.2 右下角：$$\operatorname{cov}(x_2,x_2)$$

$$
\operatorname{cov}(x_2,x_2)
=
\frac{(-1)(-1)+0\cdot0+1\cdot1}{2}
$$

$$
\frac{1+0+1}{2}
=1
$$

这就是变量 $$x_2$$ 的样本方差。

---

##### 2.6.3 右上角：$$\operatorname{cov}(x_1,x_2)$$

$$
\operatorname{cov}(x_1,x_2)
=
\frac{(-1)(-1)+0\cdot0+1\cdot1}{2}
$$

$$
\frac{1+0+1}{2}
=1
$$

---

##### 2.6.4 左下角：$$\operatorname{cov}(x_2,x_1)$$

$$
\operatorname{cov}(x_2,x_1)
=
\operatorname{cov}(x_1,x_2)
$$

所以：

$$
\operatorname{cov}(x_2,x_1)=1
$$

协方差矩阵是对称矩阵。

---

#### 2.7 最终结果

所以：

$$
C=
\begin{bmatrix}
1 & 1 \
1 & 1
\end{bmatrix}
$$

也就是代码输出：

```python
[[1. 1.]
 [1. 1.]]
```

---

#### 2.8 用矩阵形式计算

中心化矩阵：

$$
X_c=
\begin{bmatrix}
-1 & 0 & 1 \\
-1 & 0 & 1
\end{bmatrix}
$$

协方差矩阵可以写成：

$$
C=\frac{1}{N-1}X_cX_c^T
$$

先算：

$$
X_cX_c^T
=
\begin{bmatrix}
-1 & 0 & 1 \\
-1 & 0 & 1
\end{bmatrix}
\begin{bmatrix}
-1 & -1 \\
0 & 0 \\
1 & 1
\end{bmatrix}
$$

得到：

$$
X_cX_c^T
=
\begin{bmatrix}
2 & 2 \\
2 & 2
\end{bmatrix}
$$

再除以：

$$
N-1=2
$$

得到：

$$
C=
\begin{bmatrix}
1 & 1 \
1 & 1
\end{bmatrix}
$$

---

#### 2.9 直观理解

两个变量分别是：

$$
x_1=[1,2,3]
$$

$$
x_2=[4,5,6]
$$

它们的变化趋势完全一致：

$$
1 \to 2 \to 3
$$

$$
4 \to 5 \to 6
$$

也就是说：

$$
x_1 \text{ 增大时，} x_2 \text{ 也增大}
$$

$$
x_1 \text{ 减小时，} x_2 \text{ 也减小}
$$

所以它们的协方差是正数。

---

#### 2.10 一句话总结

`np.cov(X)` 做的事情是：

$$
\boxed{
\text{先对每个变量去均值，再计算变量之间的共同变化程度，最后除以 } N-1
}
$$
